INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (35, 'Tom', 'Pat');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (28, 'Harvey', 'Stone');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (46, 'Henri', 'Mets');